title: Pixelatto
email: info@pixelatto.com
description: >- # this means to ignore newlines until "baseurl:"
  Creative games and tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pixelatto.com/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pixelatto
github_username:  pixelatto
google_analytics: UA-51706081-1

# Build settings
theme: bulma-clean-theme
plugins:
  - jekyll-feed
  - jekyll-contentblocks
permalink: /:title/

paginate: 12
paginate_path: "/blog/page:num"

include: ["_redirects"]

collections:
  products:
    output: true
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  team:
    output: true
  posts:
    output: true
    permalink: blog/:slug
  presskit:
    output: true
  landings:
    output: true
  faq:
    output: true
  tags:
    output: true
    permalink: blog/tag/:slug

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
