backend:
  name: github
  repo: pixelatto/PixelattoWeb2020
  branch: master
  site_domain: pixelatto.netlify.app

media_folder: "/img/upload"
public_folder: "/img/upload"
site_url: https://pixelatto.netlify.app
logo_url: /img/brand/logo.svg
locale: 'es'

collections:
  - name: "products"
    label: "Productos"
    folder: "_products"
    preview_path: /{{slug}}
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "product"}
      - {label: "Título (H1)", name: "title", widget: "string"}
      - {label: "Subtítulo (H2)", name: "subtitle", widget: "string"}
      - {label: "Descripción", name: "description", widget: "string"}
      - {label: "Test", name: "short_description", widget: "string"}
      - label: "Features"
        name: "features"
        widget: "object"
        fields:
            - {label: Texto, name: label, widget: string}
      - label: "Imagen"
        name: "image"
        widget: "image"
        media_library:
            config:
                max_file_size: 512000
      - label: "Imagen Cabecera"
        name: "hero_image"
        widget: "image"
        media_library:
            config:
                max_file_size: 512000
      - {label: "Código", name: "product_code", widget: "string"}
      - {label: "Precio", name: "price", widget: "string"}
      - label: "Categoría"
        name: "tags"
        widget: "select"
        options: ["Games", "Software"]
      - {label: "Contenido", name: "body", widget: "markdown"}
  - name: "team"
    label: "Equipo"
    folder: "_team"
    create: true
    slug: "team/{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "member"}
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Cargo", name: "subtitle", widget: "string"}
      - {label: "Cita", name: "quote", widget: "string"}
      - {label: "Bio", name: "body", widget: "text"}
      - {label: "Teléfono", name: "telephone", widget: "string"}
      - {label: "Twitter", name: "twitter", widget: "string"}
      - label: "Avatar"
        name: "image"
        widget: "image"
        media_library:
            config:
                max_file_size: 512000
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    identifier_field: name
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Miniatura", name: "image", widget: "image"}
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Resumen", name: "summary", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime", required: false}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown", required: false}
      - {label: "Ocultar Hero", name: "hide_hero", widget: "hidden", default: "true"}
      - label: "Categorías"
        name: "tags"
        widget: "relation"
        collection: "tags"
        valueField: "tag"
        searchFields: ["tag"]
        multiple: true
        required: false

  - name: "tags"
    label: "Categorías"
    folder: "_tags"
    create: true
    identifier_files: tag
    fields:
      - {label: "Categoría", name: "tag", widget: "string"}
      - {label: "Ocultar Hero", name: "hide_hero", widget: "hidden", default: "true"}

  - name: "testimonials"
    label: "Testimonios"
    folder: "_testimonials"
    create: true
    #identifier_files: name
    fields:
      - {label: "Product Code", name: "code", widget: "string"}
      - label: "List of Tesimonials"
        name: "testimonials"
        widget: "string" # string or list?
        fields:
          - {label: "Section Title", name: "title", widget: "string", default: "Testimonials"}
          - label: "List"
            name: list
            widget: list
            fields:
              - {label: "Item Link", name: "url", widget: "string"}
              - {label: "Item Content", name: "content", widget: "string"}
              - {label: "Item Image", name: "image", widget: "image"} # image or string? required: false
              - {label: "Author Name", name: "author-name", widget: "markdown"} # markdown or string?
              - {label: "Author ID", name: "author-id", widget: "string"} # required: false
              - {label: "Author Avatar", name: "author-avatar", widget: "image"} # image or string? required: false
              - {label: "Is from Steam?", name: "from-steam", widget: "boolean", default: false}
              - {label: "Date", name: "date", widget: "datetime"} # datetime or string?
